language: php
php:
  - 5.3
  - 5.4

env:
  - DB=mysql

before_script:
  - export REPOSITORY="fluidpages"
  - git clone https://github.com/FluidTYPO3/TYPO3-Travis-Integration.git build-environment
  - source build-environment/install-utilities.sh
  - source build-environment/install-helper.sh
  - source build-environment/install-preserve-repository.sh

script:
# initial, quick inspection
  - php build-environment/FluidTYPO3-CodingStandards/commit_message_inspector.php $PWD/build-environment/repository
# phplint checking on all PHP source files in extension
  - php $PWD/typo3/cli_dispatch.phpsh extbase builder:phpsyntax --extension $REPOSITORY
# fluid template syntax checking on all files in extension
  - php $PWD/typo3/cli_dispatch.phpsh extbase builder:fluidsyntax --extension $REPOSITORY
# PHPCodeSniffer code inspection with only errors displayed (no warnings)
  - $PWD/build-environment/CodeSniffer/scripts/phpcs -n --standard=$PWD/build-environment/FluidTYPO3-CodingStandards/ruleset.xml $PWD/build-environment/repository
