language: php

sudo: false

env: COVERAGE="YES" TYPO3_VERSION=">=7.6.13, <7.6.99"

php:
  - "7.0"

matrix:
  include:
    - php: "7.0"
      env: COVERAGE="YES" TYPO3_VERSION="^8.7"
    - php: "7.1"
      env: COVERAGE="NO" TYPO3_VERSION="^8.7"
    - php: "7.0"
      env: COVERAGE="NO" TYPO3_VERSION="dev-master as 8.x-dev"
    - php: "7.1"
      env: COVERAGE="NO" TYPO3_VERSION="dev-master as 8.x-dev"

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer require "typo3/cms:$TYPO3_VERSION"
  - composer install --prefer-dist

before_script: mkdir -p build/logs

script: if [[ "$COVERAGE" != "NO" ]]; then ./vendor/bin/phpunit --coverage-clover=build/logs/clover.xml; else ./vendor/bin/phpunit; fi

after_script:
  - ln -s Classes src
  - if [[ "$COVERAGE" != "NO" ]]; then ./vendor/bin/coveralls; fi
